# NumPy : Numerical Python

# Installing and Importing numpy

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

# create numpy arrays

In [4]:
# 1D array

a = np.array([1,2,3,4,5])

In [5]:
print(a)

[1 2 3 4 5]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
# 2D array : Matrix
b = np.array([[1,2,3], [4,5,6]])

In [8]:
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3d Array: Matrix of Matrice
c = np.array([[[1,2], [3,4]] , [[5,6], [7,8]]])

In [10]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Creating Arrays with Specific Value

In [11]:
zero = np.zeros((1,3))
print(zero)

[[0. 0. 0.]]


In [12]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
zero = np.zeros((2,4))
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
one = np.ones((1,3))
print(one)

[[1. 1. 1.]]


In [15]:
one = np.ones((2,5))
print(one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
arr = np.full((3,3), 7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
arr = np.full((3,7), 100)
print(arr)

[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]]


In [18]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random number generation

In [19]:
rand_array = np.random.rand(4000,40)  # uniform distribution (0,1)
print(rand_array)

[[0.1402045  0.26163065 0.90777901 ... 0.63630502 0.59842382 0.10231208]
 [0.79125337 0.15420376 0.59979255 ... 0.72478925 0.49704817 0.90347265]
 [0.29995689 0.02701107 0.94756244 ... 0.2433005  0.16355643 0.11345023]
 ...
 [0.53828874 0.84591995 0.41932402 ... 0.31795113 0.22713568 0.15549202]
 [0.10168793 0.93196921 0.3819297  ... 0.32800837 0.40106391 0.2335541 ]
 [0.2770232  0.91770814 0.3344051  ... 0.39793913 0.94589729 0.59099885]]


In [20]:
rand_normal = np.random.randn(3,3)   # standard normal distribution
print(rand_normal)

[[-0.39447851 -0.6966446  -1.12238549]
 [-0.78520069  1.97929411  0.92795374]
 [-0.57212643  0.3687276  -0.24714115]]


In [21]:
rand_ints = np.random.randint(10, 100, (2,3))
print(rand_ints)

[[75 11 95]
 [27 81 14]]


In [22]:
rand_ints = np.random.randint(100, 1000, (6,7))
print(rand_ints)

[[596 776 581 592 228 211 385]
 [444 616 154 516 969 303 899]
 [726 345 695 236 182 816 265]
 [836 187 310 172 662 995 824]
 [984 219 813 731 273 704 409]
 [947 568 267 101 907 743 412]]


# create sequences, linear spaced value

In [23]:
arr1 = np.arange(0, 10, 2)
print(arr1)

[0 2 4 6 8]


In [24]:
arr1 = np.arange(0, 10, 3)
print(arr1)

[0 3 6 9]


In [32]:
arr2 = np.linspace(0, 10, 100)
print(arr2)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

# Array shape & Reshaping & Transpose

In [26]:
a = np.array([[1,2,3] , [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [27]:
# Reshaping
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
a  = np.arange(1,13)
b = a.reshape(3,4)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
c = b.ravel()
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
# transpose

arr = np.array([[1,2,3],
               [4,5,6]])
transpose = arr.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


# count total elements & find data types of elements

In [33]:
print(b.size)

12


In [34]:
print(b.dtype)

int32


In [38]:
arr = np.array(["apple", "bananaaaaa", "cherry"])

In [39]:
print(arr)

['apple' 'bananaaaaa' 'cherry']


In [40]:
print(arr.dtype)

<U10


# Indexing & Slicing & Modify

In [41]:
arr = np.array([[10,20,30], 
                [40,50,60]])

In [42]:
print(arr[1,2])

60


In [43]:
print(arr[0, :])

[10 20 30]


In [44]:
print(arr[ : , 1])

[20 50]


In [45]:
print(arr[-1,-2])

50


In [46]:
print(arr[-1])

[40 50 60]


In [47]:
arr[1,2] = 99
print(arr)

[[10 20 30]
 [40 50 99]]


# Statistical Operations

In [48]:
arr = np.array([[1,2,3], 
                [4,5,6]])

In [49]:
print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [50]:
print(arr * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [51]:
print(arr ** 2)

[[ 1  4  9]
 [16 25 36]]


In [52]:
print(arr.sum())

21


In [53]:
print(arr.mean())

3.5


In [58]:
arr = np.array([[10,2,3], 
                [4,50,6]])

In [54]:
print(arr.max(axis = 0))

[4 5 6]


In [55]:
print(arr.max(axis = 1))

[3 6]


In [56]:
print(arr.min(axis = 0))

[1 2 3]


In [57]:
print(arr.min(axis = 1))

[1 4]


In [59]:
print(np.sort(arr))

[[ 2  3 10]
 [ 4  6 50]]


In [60]:
arr = np.array(["bananaaaaa", "cherry", "apple"])

In [61]:
print(np.sort(arr))

['apple' 'bananaaaaa' 'cherry']


# Joining Numpy array

In [62]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [63]:
arr = np.concatenate((arr1,arr2))

In [64]:
print(arr)

[1 2 3 4 5 6]


In [66]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6], 
                 [7,8]])

In [67]:
arr = np.concatenate((arr1,arr2), axis = 1)  # row wise

In [68]:
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [69]:
arr = np.concatenate((arr1,arr2), axis = 0)  # column wise

In [70]:
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [71]:
arr = np.concatenate((arr1,arr2))  

In [72]:
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Numpy stacking & spliting

In [73]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [74]:
stacked = np.stack((arr1,arr2))

In [75]:
print(stacked)

[[1 2 3]
 [4 5 6]]


In [76]:
stacked = np.stack((arr1,arr2), axis = 1)

In [77]:
print(stacked)

[[1 4]
 [2 5]
 [3 6]]


In [78]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6], 
                 [7,8]])

In [79]:
stacked = np.stack((arr1,arr2))

In [80]:
print(stacked)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Splitting arrays

In [81]:
arr = np.array([10,20,30,40,50,60])

In [82]:
split_arr = np.split(arr, 3)

In [83]:
print(split_arr)

[array([10, 20]), array([30, 40]), array([50, 60])]
